vdb_map_converter:
	/opt/rh/devtoolset-2/root/usr/bin/g++ convertVDBtoMAP.cpp -std=c++0x -D__LINUX_COMPILE -lprotobuf -lopenvdb-gcc48_64 -lHalf -ltbb -o vdb_map_converter -L/rel/folio/openvdb/openvdb-2.3.0-6/lib/openvdb/lib/gcc48_64/ -L/rel/folio/tbb/tbb-4.3.0-3/lib/gcc48_64 -I/rel/folio/tbb/tbb-4.3.0-3/sys_include/tbb -I/rel/folio/openvdb/openvdb-2.3.0-6/include -I/rel/depot/third_party_build/boost/rhel6-1.54.0-2/include/boost-1_54
	
metaVDB:
	g++ insertMetaVDB.cpp -std=c++0x -D__LINUX_COMPILE -lprotobuf -lopenvdb -lHalf -ltbb -o insertMetaVDB -L/rel/folio/openvdb/openvdb-2.3.0-6/lib/openvdb/lib/gcc48_64/ -L/rel/folio/tbb/tbb-4.3.0-3/lib/gcc48_64 -I/rel/folio/tbb/tbb-4.3.0-3/sys_include/tbb -I/rel/folio/openvdb/openvdb-2.3.0-6/include -I/rel/depot/third_party_build/boost/rhel6-1.54.0-2/include/boost-1_54
