# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fish-gl.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fish-gl.proto',
  package='',
  serialized_pb='\n\rfish-gl.proto\"7\n\x06\x46ishGL\x12\x0f\n\x07\x66ish_id\x18\x01 \x02(\x05\x12\r\n\x05pos_x\x18\x02 \x02(\x02\x12\r\n\x05pos_y\x18\x03 \x02(\x02')




_FISHGL = _descriptor.Descriptor(
  name='FishGL',
  full_name='FishGL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fish_id', full_name='FishGL.fish_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos_x', full_name='FishGL.pos_x', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos_y', full_name='FishGL.pos_y', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['FishGL'] = _FISHGL

class FishGL(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FISHGL

  # @@protoc_insertion_point(class_scope:FishGL)


# @@protoc_insertion_point(module_scope)
